services:
  server:
    build: ./server
    networks:
      - arp
    environment:
      - USERS=${MY_USER}|${PASSWORD}
    container_name: ftp_serv

  client:
    build: ./client
    networks:
      - arp
    environment:
      - MY_USER=${MY_USER}
      - MY_PASSWORD=${PASSWORD}
    depends_on:
      - server
    container_name: ftp_client

  inquisitor:
    build:
      context: ./inquisitor
      dockerfile: Dockerfile_dev
    networks:
      - arp
    depends_on:
      - server
      - client
    volumes:
      - "./inquisitor/inquisitor.py:/app/inquisitor.py"
    container_name: inquisitor

networks:
  arp:
    driver: bridge
